version: "3.7"

services:
  app:
    build: .
    command: python main.py run -h 0.0.0.0
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="${USER}"
      - POSTGRES_PASSWORD="${PASSWORD}"
      - POSTGRES_DB="${DB}"
volumes:
  postgres_data:
